### ISSUE TITLE
Doesn't work in the latest version of Webstorm

### ISSUE THREAD

**Issue by SimplyComplexable** [tobszarny/ActiveTabHighlighterPlugin#19]
This causes a bug when starting Webstorm 2021.2 which forces Webstorm to disable the plugin altogether.

**Comment by schittli** [comment]
Good evening

The same bug happens in IntelliJ, this is the IntelliJ Exception if the Plugin is active:

```
Plugin 'com.tobszarny.activetabhighlighter.plugin.id' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: com.tobszarny.intellij.plugin.activetabhighlighter.ActiveTabHighlighterComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Active Intellij Tab Highlighter, id=com.tobszarny.activetabhighlighter.plugin.id, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.2\plugins\ActiveTabHighlighterPlugin.jar, version=1.4.0, package=null), packagePrefix=null, instanceId=23, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
    at com.a.d.c.a.bR.a(bR.java:62)
    at com.a.d.c.a.bd.a(bd.java:119)
    at com.a.d.c.a.b.a(b.java:310)
    at com.a.d.c.a.b.a(b.java:143)
    at com.a.d.c.a.b.b(b.java:93)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by tobszarny** [comment]
Still a problem?

**Comment by tobszarny** [comment]
Tested on 2021.2 on Windows. Works just fine
